services:
  - type: web
    name: fns-backend
    runtime: node
    buildCommand: PUPPETEER_SKIP_DOWNLOAD=true npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: ADMIN_PASSWORD
        generateValue: true
      - key: CORS_ORIGIN
        value: https://fns-news-decoded5.vercel.app
      - key: CHROME_PATH
        value: /usr/bin/chromium-browser