import React, { useState } from "react";
import { useNavigate } from "react-router-dom";

const Footer: React.FC = () => {
  const [showPasswordDialog, setShowPasswordDialog] = useState(false);
  const [password, setPassword] = useState("");
  const [isAdminAuthenticated, setIsAdminAuthenticated] = useState(false);
  const navigate = useNavigate();

  const handleAdminLogin = () => {
    setShowPasswordDialog(true);
  };

  const handlePasswordSubmit = () => {
    if (password === "$evenhoe$") {
      setIsAdminAuthenticated(true);
      setShowPasswordDialog(false);
      // Navigate to admin page
      navigate("/admin");
    } else {
      alert("Incorrect password");
      setPassword("");
    }
  };

  const handlePasswordCancel = () => {
    setShowPasswordDialog(false);
    setPassword("");
  };

  return (
    <>
      <footer className="bg-black/90 text-green-500 mt-12 border-t border-green-500/30 hologram-card">
        <div className="container mx-auto px-4 py-6 text-center circuit-bg">
          <p className="glow-green">
            &copy; {new Date().getFullYear()} Fragile News Source. An AI-powered
            news analysis tool.
          </p>
          <p className="text-sm mt-1 text-green-600">
            All analysis is generated by AI and should be critically reviewed.
          </p>
          <p className="text-xs mt-2">
            <button
              onClick={handleAdminLogin}
              className="text-green-700 hover:text-green-500 underline cursor-pointer transition-colors"
            >
              Admin Login
            </button>
          </p>
        </div>
      </footer>

      {/* Password Dialog */}
      {showPasswordDialog && (
        <div className="fixed inset-0 bg-black/80 flex items-center justify-center z-50">
          <div className="bg-gray-900 border border-green-500/50 rounded-lg p-6 max-w-sm w-full mx-4 hologram-card">
            <h3 className="text-green-400 text-lg font-bold mb-4">
              Admin Access
            </h3>
            <input
              type="password"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
              placeholder="Enter password"
              className="w-full bg-black border border-green-500/30 rounded px-3 py-2 text-green-400 focus:border-green-500 focus:outline-none mb-4"
              onKeyPress={(e) => e.key === "Enter" && handlePasswordSubmit()}
              autoFocus
            />
            <div className="flex justify-end space-x-2">
              <button
                onClick={handlePasswordCancel}
                className="px-4 py-2 text-green-600 hover:text-green-400 transition-colors"
              >
                Cancel
              </button>
              <button
                onClick={handlePasswordSubmit}
                className="px-4 py-2 bg-green-600 hover:bg-green-700 text-black rounded transition-colors"
              >
                Login
              </button>
            </div>
          </div>
        </div>
      )}
    </>
  );
};

export default Footer;
