
import React from 'react';

const Footer: React.FC = () => {
  return (
    <footer className="bg-black/90 text-green-500 mt-12 border-t border-green-500/30 hologram-card">
      <div className="container mx-auto px-4 py-6 text-center circuit-bg">
        <p className="glow-green">&copy; {new Date().getFullYear()} Fragile News Source. An AI-powered news analysis tool.</p>
        <p className="text-sm mt-1 text-green-600">All analysis is generated by AI and should be critically reviewed.</p>
        <p className="text-xs mt-2 text-green-700">Building Skynet to prevent Skynet - Ethical AI for Social Justice</p>
      </div>
    </footer>
  );
};

export default Footer;
